<script>
        require(['jquery'], function($) {
            $(document).ready(function($){
				let date = new Date();
				let options = {timeZone: 'America/New_York',hour12: false,hour: '2-digit'};
				let eastCoastTime = date.toLocaleString('en-US', options);
				console.log(eastCoastTime);
				/*if(eastCoastTime < 9 || eastCoastTime >= 23){
					$('button.checkout').attr('disabled', 'disabled');
					$('button.checkout').css('color', '#000');
					$('button.checkout').css('background-color', '#fff');
					$('button.checkout span').replaceWith("Orders can only be placed between the hours of 9 AM and 11 PM");
					
				}*/
			 var todayNY = new Date().toLocaleString("en-US", {timeZone: "America/New_York"});
				todayNY = new Date(todayNY);
				if (todayNY.getDay() == 7) {
				  $('button.checkout').attr('disabled', 'disabled');
				  $('button.checkout').css('color', '#000');
				  $('button.checkout').css('background-color', '#fff');
				  $('button.checkout span').replaceWith("Sales not allowed on sunday");
				}
			});
        });</script>