<?php
$blockObj= $block->getLayout()->createBlock('Burstonline\Customconfig\Block\Customconfig');
$splashConfig=$blockObj->getSplashImage();
?>
<?php if ( $block->enableDisable() ) : ?>
    <?php
    if ( $block->getType() == 'v-bar' ) {
        $width = '93%';
    } else {
        $width = '100%';
    }
    $fontFamily = $block->headerTextFontFamily();
    $fontFamily = str_replace('+', ' ', $fontFamily);
    $fontFamily = "font-family:'" . $fontFamily . "';";
    $splashbg = $block->getViewFileUrl('Meetanshi_CookieNotice::images/splashbg.png');
    ?>
    <div id="m-cookienotice"
         class="<?php echo $block->getType(); ?> <?php echo ($block->getType() == 'v-bar') ? $block->getBarPosition() : $block->getBoxPosition(); ?>"
         style="display:block; text-align:<?php echo $block->modelTextAlign(); ?>;
                 background: #fce160;background-repeat: no-repeat; background-size : 50%; background-position: right bottom; color:#387E7E;
         <?php if ( $block->modelBorder() ) :
             ?> border-color:<?php echo $block->modelBorderColor();
if ( $block->headerBottomBorder() ) :
    ?>; border-bottom-color:<?php echo $block->headerBottomBorderColor();
endif;
if ( $block->containerTopBorder() ) :
    ?>; border-top-color:<?php echo $block->containerTopBorderColor();
endif;
         else :
             ?>border:0px;<?php
         endif; ?>;">
        <div id="splashloading" style="margin-top:45vh">
            <img src="<?php echo $block->getViewFileUrl('Meetanshi_CookieNotice::images/loader-1.gif');?>" />
        </div>
        <div id="splashcontent" style="display:none;">
        <div class="m-message title"
             style="font-weight:bold;width:<?php echo $width ?>;font-size:<?php echo $block->modelTitleFontSize() ?>px;color:<?php echo $block->modelTitleColor(); ?>;<?php echo $fontFamily ?>">
            <span class="titlecookie"
                  style="border-bottom: 2px solid <?php echo $block->acceptButtonBackgroundColor() ?>;">
            <?php if ( $block->getShow() == 'default' ) :
                echo 'Cookies and Privacy';
            else :
                echo $block->modelTitle();
            endif;
            ?>
                </span>
        </div>
        <div class="splashtext">
            <img src="<?php echo $block->getViewFileUrl('Meetanshi_CookieNotice::images/welcometxt.png');?>" style="width: 60%;" />
            <div id="message-custom-css" class="m-message custom-css"
                style="width:<?php echo $width ?>;font-size:<?php echo $block->modelMessageSize(); ?>px;<?php echo $fontFamily ?>">
                <?php if ( $block->getShow() == 'default' ) :
                    echo 'This website use cookies to ensure you get the best user experience on our website.';
                else :
                    echo "<h1>".$block->getCustomMessage()."</h1>";
                endif;
                ?>
                <a href="javascript:cookieNoticeAccept();" class="m-button m-accept">
                    <?php if ( $block->getShow() == 'default' ) :
                        echo "ACCEPT AND ENTER";
                    else :
                        echo $block->getCustomAccept();
                    endif;
                    ?>
                </a>
                <div class="splashfooter">
                    <img src="<?php echo $block->getViewFileUrl('Meetanshi_CookieNotice::images/footerlogos.png');?>" style="width: 150px;" />
                    <span style="font-size: 25px;color: #000;">|</span>
                    <?php if($splashConfig['enabled']==1): ?> 
                    	<img src="<?php echo $splashConfig['splash_image'];?>" style="width: 150px;" />
                    <?php else:?>
						<img src="<?php echo $block->getViewFileUrl('Meetanshi_CookieNotice::images/footerlogos1.png');?>" style="width: 150px;" />
                    <?php endif; ?>
                </div>
            </div>
                    </div>
        </div>
    </div>
    <div id="v-badge" class="v-badge" onClick="showDiv()" style="display:none">Cookie Settings</div>
    <script type="text/javascript">
        <?php \Magento\Framework\App\ObjectManager::getInstance()->get('Psr\Log\LoggerInterface')->info($block->getBehaviour()); ?>
        <?php \Magento\Framework\App\ObjectManager::getInstance()->get('Psr\Log\LoggerInterface')->info($block->onscroll()); ?>
        <?php \Magento\Framework\App\ObjectManager::getInstance()->get('Psr\Log\LoggerInterface')->info($block->getAutoExpire()); ?>
        var behaviour = <?php echo $block->getBehaviour(); ?>;
        var onScroll =<?php echo $block->onscroll() ?>;
        var expire =<?php echo $block->getAutoExpire() ?>;
        if (expire == 0) {
            expire = 1;
        } else {
            expire =<?php echo $block->getAutoExpire() ?>;
        }

        if (onScroll == 1) {
            window.onscroll = function () {
                custom()
            };
        }

        function custom() {
            if (document.getElementById('m-cookienotice').style.display == 'block') {
                //document.getElementById('m-cookienotice').style.backgroundColor == '#387E7E';
                if (behaviour) {
                    var d = new Date();
                    d.setTime(d.getTime() + (behaviour + expire * 24 * 60 * 60 * 1000));
                    var expires = "expires=" + d.toUTCString();
                    document.getElementById('splashloading').style.display = "none";
                    document.getElementById('splashcontent').style.display = "block";

                }
                if (document.body.scrollTop > 150 || document.documentElement.scrollTop > 150) {
                    document.cookie = "cookienotice" + "=" + "true" + ";" + expires + ";path=/";
                    document.getElementById('m-cookienotice').style.display = 'none';
                    document.getElementById('splashloading').style.display = "block";
                    document.getElementById('splashcontent').style.display = "none";
                }
            }
        }

        function showDiv() {
            document.getElementById('m-cookienotice').style.display = "block";
            //document.getElementById('m-cookienotice').style.backgroundColor == '#387E7E';
            document.getElementById('splashloading').style.display = "none";
            document.getElementById('splashcontent').style.display = "block";
            document.getElementById('v-badge').style.display = 'none';
        }

        function cookieClose() {
            document.getElementById('v-badge').style.display = 'block';
            document.getElementById('m-cookienotice').style.display = 'none';
            document.getElementById('splashloading').style.display = "block";
            document.getElementById('splashcontent').style.display = "none";
        }

        function cookieNoticeAccept() {
            if (behaviour) {
                var d = new Date();
                d.setTime(d.getTime() + (behaviour + expire * 24 * 60 * 60 * 1000));
                var expires = "expires=" + d.toUTCString();

            }
            document.cookie = "cookienotice" + "=" + "true" + ";" + expires + ";path=/";
            document.getElementById('m-cookienotice').style.display = 'none';
            document.getElementById('splashloading').style.display = "block";
            document.getElementById('splashcontent').style.display = "none";
        }

        require([
            'jquery',
            'mage/cookies'
        ], function ($) {
            if ($.cookie('cookienotice')) { 
                document.getElementById('m-cookienotice').style.display = 'none';
                document.getElementById('splashloading').style.display = "block";
                document.getElementById('splashcontent').style.display = "none";
            }
            else {
                //document.getElementById('m-cookienotice').style.backgroundColor == '#387E7E';
                document.getElementById('m-cookienotice').style.display = 'block';
                document.getElementById('splashloading').style.display = "none";
                document.getElementById('splashcontent').style.display = "block";
            }
        });

        <?php if ($block->getAutohide()) : ?>
        setTimeout(function () {
            document.getElementById('m-cookienotice').style.display = 'none';
            document.getElementById('splashloading').style.display = "block";
                document.getElementById('splashcontent').style.display = "none";
        }, <?php echo $block->getAutohide() * 1000; ?>);
        <?php endif; ?>
        <?php if ($block->getAutoAccept()) : ?>
        setTimeout(function () {
            cookieNoticeAccept();
        }, <?php echo $block->getAutoAccept() * 1000; ?>);
        <?php endif; ?>
    </script>

<?php endif; ?>
