<div class='epi'>
	<div class='errors'>
		<?php if($this->getMessages()): ?>
				<!-- <div class='alert alert-danger'><p style='color:red'></p></div> -->
				<?php foreach($this->getMessages() as $message): ?>
				<div class='alert alert-danger'><p style='color:red'><?= $message ?></p></div>
			<?php endforeach; ?>
			<?php if($this->getShowPhoneBox()): ?>
				<form method='post'>
					<label>Telephone</label><input type='text' name='telephone' value='<?php echo $this->getTelephone() ?>' />
					<div><input type='submit' class='btn btn-primary' value='UPDATE TELEPHONE'></div>
				</form>
			<?php endif; ?>
		<?php else: ?>
			<div style="width:200px;margin:auto;margin-top:20px">
			<img style="width:100%" src="<?php echo $block->getViewFileUrl('Epi_EpiPay::images/spinner.gif'); ?>">
			<center>Redirecting you to EpiPay</center>
			</div>
			<form name='epi' action='<?= $this->getAction() ?>'>
				<?php if($this->getOrderId()): ?>
					<input type='hidden' name='id' value='<?= $this->getOrderId() ?>'>
					<input type='hidden' name='token' value='<?= $this->getToken() ?>'>
					<input type='hidden' name='expireAt' value='<?= $this->getExpireAt() ?>'>
				<?php endif; ?>
			</form>
			<script>
				 document.addEventListener("DOMContentLoaded", function(event) {
			document.epi.submit();
            });  
				
			</script>
		<?php endif; ?>
	</div>
	
</div>