<div class="browsecategory">
	<h1>Browse by category</h1>
	<div class="categorieslist row">
		<?php 
		$catDetails=$block->getCategories();
		 $k=0; $categoryCount = count($catDetails);
		foreach($catDetails as $cat) { ?>
			<?php $lastCategory = ($k == $categoryCount-1) ? 'last-category' : '';
				  $SecondCategory = ($k == 1) ? 'second-category' : ''; ?>
			<a href="<?php echo $cat['url']?>">							
				<div class="col-md-2 col-sm-4 col-6 category-wrapper <?php echo $lastCategory." ".$SecondCategory; ?>">
					<div class="category-container <?php echo strtolower($cat['name']);?>">
					<div class="image">
						<?php $result = preg_replace('/[ ]+/', '-', trim(strtolower($cat['name'])));
						$img=$block->getViewFileUrl('Burstonline_Customhome::images/category/'.$result.'.png');
						?>
						<img src="<?php echo $img;?>">
													
					</div>
					<div class="text">
						<h1><?php echo $cat['name']?></h1>
					</div>
					</div>
				</div>
			</a>
		<?php $k++;
		 } ?>
	</div>
	<div class="browsealldiv"><a href="" class="browseall">Browse All</a></div>
</div>
<style>
	.category-container:hover{background-color:#FBE053;}
	.category-wrapper{padding: 10px;float: left;margin-top:20px;}
.category-container {display: flex;align-items: center;border:1px solid #e6e6e6;box-shadow:2px 3px 3px 2px #e6e6e6;background-color:#fff;}

.browsecategory h1{text-align:center;font-family:CinzelSemiBold;font-weight:400;font-size:0.3em;}
.browsecategory > h1{font-size:3em;margin-bottom:20px;}
.browsecategory h1 a{text-decoration:none;color:#000;}
.category-container img {	max-width: 100%;max-height:100%;}
.category-container .text {
  font-size: 60px;padding:20px;margin:0 auto;
}
.browsecategory{background-color:#f3f3f3;text-align:center;padding: 15px 60px 30px 60px;}
.browsealldiv{margin-top:17px;}
.browseall{margin-top:50px;background-color: #FBE053;padding: 10px 20px;font-family: CinzelSemiBold;color: #000;text-decoration: none;font-size: 1.5em;}
.browseall:visited{color:#000;}

.categorieslist,.shopcategory{display:inline-block;}
.categorieslist{width: 100%;margin: 0 auto;}
.category-container{height: 110px;width: 150px;position: relative;}
.category-container .image{position: absolute;top: -30px;right: 0;left:0;width:50px;  left: 50%;transform: translateX(-50%);}
.category-container.cigars .image{top: -50px;width: 43px;}

@media (min-width: 1280px){
	.browsecategory .categorieslist{width:1280px;}
}

@media (max-width: 1200px){
	.browsecategory h1{font-size:0.2em;}
	.browsecategory > h1{font-size:3em;}
}
@media (min-width: 768px){
	.last-category{
		margin-top : 5px;
	}
}
@media (max-width: 768px){
	.second-category{
		margin-top : 5px;
	}
}
</style>


